---
- name: Set MySQL root password before installing
  become: yes
  debconf: name='mysql-server' question='mysql-server/root_password' value='{{mysql_root_password}}' vtype='password'

- name: Confirm MySQL root password before installing
  become: yes
  debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{mysql_root_password}}' vtype='password'

- name: Install MySQL
  become: yes
  apt: package={{ item }} state=installed force=yes update_cache=yes cache_valid_time=3600
  with_items:
    - mysql-server
    - libmysqlclient-dev
    - python-mysqldb

- name: Deletes anonymous MySQL server user for localhost
  mysql_user: user="" state="absent" login_password="{{ mysql_root_password }}" login_user=root

- name: Secures the MySQL root user
  mysql_user: user="root" password="{{ mysql_root_password }}" host="{{ item }}" login_password="{{mysql_root_password}}" login_user=root
  with_items:
    - 127.0.0.1
    - localhost
    - ::1
    - "{{ ansible_fqdn }}"

- name: Removes the MySQL test database
  mysql_db: db=test state=absent login_password="{{ mysql_root_password }}" login_user=root

- name: Create app database user
  mysql_user: name='{{database_user_name}}'
              password='{{database_user_password}}'
              priv='{{database_name}}.*:ALL'
              login_password="{{ mysql_root_password }}"
              login_user=root state=present

- name: Create a new database with name '{{database_name}}'
  mysql_db: name='{{database_name}}' login_password="{{ database_user_password }}" login_user={{database_user_name}} state=present state=present

