ansistrano_deploy_from: "{{ playbook_dir }}/../../" # Where my local project is (relative or absolute path)
ansistrano_deploy_to: "{{ deploy_directory }}" # Base path to deploy to.
ansistrano_keep_releases: 3 # Releases to keep after a new deployment. See "Pruning old releases".

# Arrays of directories and files to be shared.
# The following arrays of directories and files will be symlinked to the current release directory after the 'update-code' step and its callbacks
# Notes:
# * Paths are relative to the /shared directory (no starting /)
# * If your items are in a subdirectory, write the entire path to each shared directory
#
# Example:
# ansistrano_shared_paths:
#   - path/to/first-dir
#   - path/next-dir
# ansistrano_shared_files:
#   - my-file.txt
#   - path/to/file.txt
ansistrano_shared_paths: [tmp/sockets, log, config/puma]
ansistrano_shared_files: []

ansistrano_deploy_via: "git" # Method used to deliver the code to the server.
ansistrano_allow_anonymous_stats: yes

# Variables used in the Git deployment strategy
ansistrano_git_repo: https://github.com/andrecastro/test-deploy-ansible-rails.git # Location of the git repository
ansistrano_git_branch: master # What version of the repository to check out. This can be the full 40-character SHA-1 hash, the literal string HEAD, a branch name, or a tag name

# Variables used in the download deployment strategy
#ansistrano_get_url: https://github.com/someproject/somearchive.tar.gz

# Hooks: custom tasks if you need them
ansistrano_after_symlink_tasks_file: "{{ playbook_dir }}/roles/deployer/tasks/after_symlink.yaml"

