# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7025a751e18e43c9acc44429025e6ae15ca09e5a087e131c433c2de539ae72fefb48ba7e7e2da46b00b46c49cfee2fdbebea0f7c669909addf04d01e073d20ff

test:
  secret_key_base: 8c1c6f66fb70b867f986d92e6b1d79550b7ca0e488fc7d2589c76f7d445f3c0eeabc6086fbcdfef3849865ded78d347db862575dbf684fa351f0010327618756

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
