---
- name: Install nginx
  become: yes
  apt: pkg=nginx state=latest

- name: Remove the default app - available
  become: yes
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: Remove the default app - enabled
  become: yes
  file: path=/etc/nginx/sites-available/default state=absent

- name: Remove the app's config, if exists
  become: yes
  file: path=/etc/nginx/sites-available/{{app_name}}  state=absent

- name: Remove the app's symlink, if exists
  become: yes
  file: path=/etc/nginx/sites-enabled/{{app_name}} state=absent

- name: Configure nginx for the app
  become: yes
  template: src=nginx/etc/nginx/sites-available/app.conf.j2 dest=/etc/nginx/sites-available/{{app_name}} force=yes

- name: Enable the app
  become: yes
  file: src=/etc/nginx/sites-available/{{app_name}} dest=/etc/nginx/sites-enabled/{{app_name}} state=link

- name: Restart nginx
  action: service name=nginx state=restarted