---
- name: Add puma init script
  become: yes
  template: src=puma/etc/init/puma.conf.j2 dest=/etc/init/puma.conf force=yes mode=755
  tags: puma

- name: Add puma shared/config
  template: src=puma/production.rb.j2 dest={{deploy_directory}}/shared/config/puma/production.rb force=yes mode=755
  tags: puma

- name: Make shared/tmp/sockets
  become: yes
  file: path={{deploy_directory}}/shared/tmp/sockets state=directory
  tags: tmp